#############################################################################
# Makefile for building: ganids_gui
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue May 1 12:44:23 2012
# Project:  ganids_gui.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ganids_gui.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../boost-1.49.0/include -I../re2 -I../sqlite-amalgamation-3071100 -I/opt/cuda-toolkit/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu
LIBS          = $(SUBLIBS)  -L/opt/cuda-toolkit/lib64 -L/usr/lib -L../boost-1.49.0/lib -lpcap -lboost_log -lboost_filesystem -lboost_system -lboost_date_time -lboost_thread -lboost_regex -L../re2/obj -lre2 -L../sqlite-amalgamation-3071100 -lsqlite3 -lcudart -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ganidsmainwindow.cpp \
		trie_node.cpp \
		trie.cpp \
		rule.cpp \
		regex.cpp \
		packet.cpp \
		nids.cpp \
		common.cpp \
		ac.cpp \
		capturethread.cpp \
		db.cpp moc_ganidsmainwindow.cpp
OBJECTS       = ${OBJECTS_DIR}my_nids_cuda.o \
		main.o \
		ganidsmainwindow.o \
		trie_node.o \
		trie.o \
		rule.o \
		regex.o \
		packet.o \
		nids.o \
		common.o \
		ac.o \
		capturethread.o \
		db.o \
		moc_ganidsmainwindow.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/declarative_debug.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		ganids_gui.pro
QMAKE_TARGET  = ganids_gui
DESTDIR       = 
TARGET        = ganids_gui

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_ganidsmainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: ganids_gui.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/declarative_debug.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ganids_gui.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/declarative_debug.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ganids_gui.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ganids_gui1.0.0 || $(MKDIR) .tmp/ganids_gui1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ganids_gui1.0.0/ && $(COPY_FILE) --parents my_nids_cuda.cu .tmp/ganids_gui1.0.0/ && $(COPY_FILE) --parents ganidsmainwindow.h trie_node.h trie.h rule_spirit.h rule.h regex.h packet.h nids.h my_nids_cuda.h grammar.h common.h ac.h capturethread.h db.h .tmp/ganids_gui1.0.0/ && $(COPY_FILE) --parents main.cpp ganidsmainwindow.cpp trie_node.cpp trie.cpp rule.cpp regex.cpp packet.cpp nids.cpp common.cpp ac.cpp capturethread.cpp db.cpp .tmp/ganids_gui1.0.0/ && $(COPY_FILE) --parents ganidsmainwindow.ui .tmp/ganids_gui1.0.0/ && (cd `dirname .tmp/ganids_gui1.0.0` && $(TAR) ganids_gui1.0.0.tar ganids_gui1.0.0 && $(COMPRESS) ganids_gui1.0.0.tar) && $(MOVE) `dirname .tmp/ganids_gui1.0.0`/ganids_gui1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ganids_gui1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_cuda_make_all: ${OBJECTS_DIR}my_nids_cuda.o
compiler_cuda_clean:
	-$(DEL_FILE) ${OBJECTS_DIR}my_nids_cuda.o
${OBJECTS_DIR}my_nids_cuda.o: my_nids_cuda.cu \
		my_nids_cuda.cu \
		/usr/include/bits/huge_val.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/local_lim.h \
		/usr/include/bits/wordsize.h \
		/usr/include/c++/4.7.0/ext/type_traits.h \
		/opt/cuda-toolkit/include/cuda_surface_types.h \
		/usr/include/bits/types.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/c++/4.7.0/bits/cpp_type_traits.h \
		/usr/include/sys/cdefs.h \
		/usr/include/c++/4.7.0/exception \
		/usr/include/bits/waitflags.h \
		/opt/cuda-toolkit/include/device_launch_parameters.h \
		/opt/cuda-toolkit/include/sm_20_intrinsics.h \
		/opt/cuda-toolkit/include/cuda_runtime.h \
		/opt/cuda-toolkit/include/common_functions.h \
		my_nids_cuda.h \
		/opt/cuda-toolkit/include/cuda_texture_types.h \
		/opt/cuda-toolkit/include/sm_20_atomic_functions.h \
		/usr/include/limits.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/sigset.h \
		/opt/cuda-toolkit/include/texture_fetch_functions.h \
		/usr/include/c++/4.7.0/x86_64-unknown-linux-gnu/bits/c++config.h \
		/usr/include/linux/limits.h \
		/usr/include/c++/4.7.0/x86_64-unknown-linux-gnu/bits/cpu_defines.h \
		/usr/include/bits/typesizes.h \
		/opt/cuda-toolkit/include/math_functions_dbl_ptx1.h \
		/usr/include/c++/4.7.0/x86_64-unknown-linux-gnu/bits/os_defines.h \
		/opt/cuda-toolkit/include/device_functions.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/c++/4.7.0/bits/atomic_lockfree_defines.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/timex.h \
		/usr/include/stdlib.h \
		/usr/include/c++/4.7.0/cstdlib \
		/opt/cuda-toolkit/include/math_functions.h \
		/usr/include/sys/select.h \
		/usr/include/c++/4.7.0/new \
		/opt/cuda-toolkit/include/sm_11_atomic_functions.h \
		/opt/cuda-toolkit/include/vector_functions.h \
		/usr/include/bits/time.h \
		/usr/lib/gcc/x86_64-unknown-linux-gnu/4.7.0/include/stddef.h \
		/opt/cuda-toolkit/include/surface_functions.h \
		/opt/cuda-toolkit/include/device_types.h \
		/usr/include/bits/pthreadtypes.h \
		/opt/cuda-toolkit/include/sm_30_intrinsics.h \
		/usr/include/bits/select.h \
		/usr/include/gnu/stubs.h \
		/opt/cuda-toolkit/include/sm_13_double_functions.h \
		/opt/cuda-toolkit/include/driver_functions.h \
		/opt/cuda-toolkit/include/host_config.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/usr/include/endian.h \
		/opt/cuda-toolkit/include/sm_12_atomic_functions.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/string.h \
		/usr/include/xlocale.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/time.h \
		/usr/include/alloca.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/usr/include/bits/xopen_lim.h \
		/opt/cuda-toolkit/include/cuda.h \
		/usr/include/math.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/c++/4.7.0/cmath \
		/opt/cuda-toolkit/include/channel_descriptor.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/usr/lib/gcc/x86_64-unknown-linux-gnu/4.7.0/include-fixed/limits.h \
		/usr/include/features.h \
		/usr/lib/gcc/x86_64-unknown-linux-gnu/4.7.0/include-fixed/syslimits.h \
		/opt/cuda-toolkit/include/cuda_runtime_api.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/sys/types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/channel_descriptor.h \
		/opt/cuda-toolkit/include/cuda_runtime_api.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/host_config.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/channel_descriptor.h \
		/opt/cuda-toolkit/include/cuda_runtime_api.h \
		/opt/cuda-toolkit/include/driver_functions.h \
		/opt/cuda-toolkit/include/vector_functions.h \
		/opt/cuda-toolkit/include/common_functions.h \
		/opt/cuda-toolkit/include/math_functions.h \
		/opt/cuda-toolkit/include/math_constants.h \
		/opt/cuda-toolkit/include/device_functions.h \
		/opt/cuda-toolkit/include/sm_11_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_12_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_13_double_functions.h \
		/opt/cuda-toolkit/include/sm_20_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_20_intrinsics.h \
		/opt/cuda-toolkit/include/sm_30_intrinsics.h \
		/opt/cuda-toolkit/include/surface_functions.h \
		/opt/cuda-toolkit/include/cuda_surface_types.h \
		/opt/cuda-toolkit/include/texture_fetch_functions.h \
		/opt/cuda-toolkit/include/cuda_texture_types.h \
		/opt/cuda-toolkit/include/math_functions_dbl_ptx1.h \
		/opt/cuda-toolkit/include/math_functions_dbl_ptx3.h \
		/opt/cuda-toolkit/include/device_launch_parameters.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/math_functions.h \
		/opt/cuda-toolkit/include/math_constants.h \
		/opt/cuda-toolkit/include/device_functions.h \
		/opt/cuda-toolkit/include/sm_11_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_12_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_13_double_functions.h \
		/opt/cuda-toolkit/include/sm_20_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_20_intrinsics.h \
		/opt/cuda-toolkit/include/sm_30_intrinsics.h \
		/opt/cuda-toolkit/include/surface_functions.h \
		/opt/cuda-toolkit/include/cuda_surface_types.h \
		/opt/cuda-toolkit/include/channel_descriptor.h \
		/opt/cuda-toolkit/include/cuda_runtime_api.h \
		/opt/cuda-toolkit/include/vector_functions.h \
		/opt/cuda-toolkit/include/texture_fetch_functions.h \
		/opt/cuda-toolkit/include/cuda_texture_types.h \
		/opt/cuda-toolkit/include/math_functions_dbl_ptx1.h \
		/opt/cuda-toolkit/include/math_functions_dbl_ptx3.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/channel_descriptor.h \
		/opt/cuda-toolkit/include/cuda_runtime_api.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/cuda_texture_types.h \
		/opt/cuda-toolkit/include/channel_descriptor.h \
		/opt/cuda-toolkit/include/cuda_runtime_api.h \
		/opt/cuda-toolkit/include/vector_functions.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/sm_11_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_12_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_13_double_functions.h \
		/opt/cuda-toolkit/include/sm_20_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_20_intrinsics.h \
		/opt/cuda-toolkit/include/sm_30_intrinsics.h \
		/opt/cuda-toolkit/include/surface_functions.h \
		/opt/cuda-toolkit/include/cuda_surface_types.h \
		/opt/cuda-toolkit/include/channel_descriptor.h \
		/opt/cuda-toolkit/include/cuda_runtime_api.h \
		/opt/cuda-toolkit/include/vector_functions.h \
		/opt/cuda-toolkit/include/texture_fetch_functions.h \
		/opt/cuda-toolkit/include/cuda_texture_types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/math_constants.h \
		/opt/cuda-toolkit/include/device_functions.h \
		/opt/cuda-toolkit/include/sm_11_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_12_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_13_double_functions.h \
		/opt/cuda-toolkit/include/sm_20_atomic_functions.h \
		/opt/cuda-toolkit/include/sm_20_intrinsics.h \
		/opt/cuda-toolkit/include/sm_30_intrinsics.h \
		/opt/cuda-toolkit/include/surface_functions.h \
		/opt/cuda-toolkit/include/cuda_surface_types.h \
		/opt/cuda-toolkit/include/channel_descriptor.h \
		/opt/cuda-toolkit/include/cuda_runtime_api.h \
		/opt/cuda-toolkit/include/vector_functions.h \
		/opt/cuda-toolkit/include/texture_fetch_functions.h \
		/opt/cuda-toolkit/include/cuda_texture_types.h \
		/opt/cuda-toolkit/include/math_functions_dbl_ptx1.h \
		/opt/cuda-toolkit/include/math_functions_dbl_ptx3.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/cuda_surface_types.h \
		/opt/cuda-toolkit/include/channel_descriptor.h \
		/opt/cuda-toolkit/include/cuda_runtime_api.h \
		/opt/cuda-toolkit/include/vector_functions.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/cuda_runtime_api.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/usr/lib/gcc/x86_64-unknown-linux-gnu/4.7.0/include-fixed/syslimits.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/builtin_types.h \
		/opt/cuda-toolkit/include/device_types.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/surface_types.h \
		/opt/cuda-toolkit/include/texture_types.h \
		/opt/cuda-toolkit/include/vector_types.h \
		/opt/cuda-toolkit/include/host_defines.h \
		/opt/cuda-toolkit/include/driver_types.h \
		/opt/cuda-toolkit/include/host_defines.h
	/opt/cuda-toolkit/bin/nvcc -m64 -g -G -arch=sm_11 -c --compiler-options -fno-strict-aliasing -use_fast_math --ptxas-options=-v -I../boost-1.49.0/include -I../re2 -I../sqlite-amalgamation-3071100 -I/opt/cuda-toolkit/include -L../boost-1.49.0/lib -lpcap -lboost_log -lboost_filesystem -lboost_system -lboost_date_time -lboost_thread -lboost_regex -L../re2/obj -lre2 -L../sqlite-amalgamation-3071100 -lsqlite3 -lcudart my_nids_cuda.cu -o ${OBJECTS_DIR}my_nids_cuda.o

compiler_moc_header_make_all: moc_ganidsmainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ganidsmainwindow.cpp
moc_ganidsmainwindow.cpp: nids.h \
		trie.h \
		common.h \
		trie_node.h \
		rule.h \
		rule_spirit.h \
		packet.h \
		ac.h \
		regex.h \
		db.h \
		capturethread.h \
		ganidsmainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ganidsmainwindow.h -o moc_ganidsmainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ganidsmainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ganidsmainwindow.h
ui_ganidsmainwindow.h: ganidsmainwindow.ui
	/usr/bin/uic ganidsmainwindow.ui -o ui_ganidsmainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_cuda_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ganidsmainwindow.h \
		nids.h \
		trie.h \
		common.h \
		trie_node.h \
		rule.h \
		rule_spirit.h \
		packet.h \
		ac.h \
		regex.h \
		db.h \
		capturethread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ganidsmainwindow.o: ganidsmainwindow.cpp ganidsmainwindow.h \
		nids.h \
		trie.h \
		common.h \
		trie_node.h \
		rule.h \
		rule_spirit.h \
		packet.h \
		ac.h \
		regex.h \
		db.h \
		capturethread.h \
		ui_ganidsmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ganidsmainwindow.o ganidsmainwindow.cpp

trie_node.o: trie_node.cpp trie_node.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trie_node.o trie_node.cpp

trie.o: trie.cpp trie.h \
		common.h \
		trie_node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trie.o trie.cpp

rule.o: rule.cpp common.h \
		rule.h \
		rule_spirit.h \
		trie.h \
		trie_node.h \
		grammar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rule.o rule.cpp

regex.o: regex.cpp regex.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o regex.o regex.cpp

packet.o: packet.cpp common.h \
		packet.h \
		rule_spirit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o packet.o packet.cpp

nids.o: nids.cpp common.h \
		nids.h \
		trie.h \
		trie_node.h \
		rule.h \
		rule_spirit.h \
		packet.h \
		ac.h \
		regex.h \
		db.h \
		my_nids_cuda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nids.o nids.cpp

common.o: common.cpp common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o common.o common.cpp

ac.o: ac.cpp ac.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ac.o ac.cpp

capturethread.o: capturethread.cpp capturethread.h \
		nids.h \
		trie.h \
		common.h \
		trie_node.h \
		rule.h \
		rule_spirit.h \
		packet.h \
		ac.h \
		regex.h \
		db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o capturethread.o capturethread.cpp

db.o: db.cpp db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db.o db.cpp

moc_ganidsmainwindow.o: moc_ganidsmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ganidsmainwindow.o moc_ganidsmainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

